{% set name = "numba-scipy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 443645d6635c667adc3b38d0a636d9abcc971e78de2c07808d89afcd7bc58444

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numba >=0.45
    - scipy >=0.16,<=1.11.0
    - setuptools

test:
  requires:
    - pip
    - numpy =1.22
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - numba_scipy
    - numba_scipy.special

about:
  home: https://github.com/numba/numba-scipy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: numba-scipy extends Numba to make it aware of SciPy

extra:
  recipe-maintainers:
    - xhochy
